version: '3'
services:
  postgresql:
    image: "ionx/postgres-plv8:12.2"
    ports:
     - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: marten_testing
      NAMEDATALEN: 100
  sqlserver:
    image: "microsoft/mssql-server-linux"
    ports:
      - "1433:1433"
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=P@55w0rd"
      - "MSSQL_PID=Developer"

