name: MSSQL CI build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  config: Release
  disable_test_parallelization: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  db_name: weasel_testing
  # db_user: test_user
  # db_pwd: P@55w0rd

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 30

    # services:
    #   sqlserver:
    #     image: mcr.microsoft.com/mssql/server:2019-latest
    #     ports:
    #       - 1433:1433
    #     env:
    #       ACCEPT_EULA: Y
    #       SA_PASSWORD: ${{ env.db_pwd }}
    #       MSSQL_PID: ${{ env.db_user }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      env:
        # weasel_sqlserver_testing_database: "Server=localhost;Database=${{ env.db_name }};User Id=${{ env.db_user }};Password=${{ env.db_pwd }};"
        weasel_sqlserver_testing_database: "Server=(localdb)\\MSSQLLocalDB;Integrated Security=true"
      run: dotnet test src/Weasel.SqlServer.Tests/Weasel.SqlServer.Tests.csproj --no-build --verbosity normal
